vscode --install-extension formulahendry.code-runner
vscode --install-extension ms-azuretools.vscode-docker
vscode --install-extension ms-vscode.cpptools
vscode --install-extension ms-vscode-remote.remote-wsl
vscode --install-extension ms-vscode-remote.remote-ssh
vscode --install-extension ms-vscode-remote.remote-ssh-edit
vscode --install-extension ms-python.python
vscode --install-extension ms-python.vscode-pylance
vscode --install-extension ms-toolsai.jupyter
vscode --install-extension xaver.clang-format
vscode --install-extension notskm.clang-tidy
vscode --install-extension platformio.platformio-ide
vscode --install-extension smockle.xcode-default-theme
vscode --install-extension GitHub.github-vscode-theme
vscode --install-extension twxs.cmake
vscode --install-extension yzhang.markdown-all-in-one
vscode --install-extension matthewevers.compiler-explorer
